### ISSUE TITLE
Swap old tasks to first half, so 50-75 is free for new tasks

### ISSUE THREAD

**Issue by Savallator** [enowars/EnoEngine#35]

**Comment by Trolldemorted** [comment]
I recommend you sort out #27 first, so you have a nice visual representation of what is happening when

**Comment by Trolldemorted** [comment]
@MMunier and I plotted your task starts (putflag=0, getflag=1, putnoise=2, getnoise=3, havoc=4) in a visualization which is automatically applied in your ELK:
![grafik](https://user-images.githubusercontent.com/10261186/86601457-a2314800-bfa1-11ea-8d9e-8f2ae3821220.png)

The results are roughly what we expected: Q1 has all putflags and getflags, Q2 has only havoc and getflags for old rounds, Q3 has all getflags for the current round and all getnoises, Q4 has no new tasks.

## Improvements
### Increase Q2 Load
Q2 has measurably less load than Q1 and Q3, so we could move getoldflags/havocs from Q1 and Q3 to Q2.
### Safety Margins
As you can see at the end of Q1, the getcurrentflags/getnoises tasks are started with a safety margin of 5s to the end of the quarter, while the getoldflags/havoc tasks aren't, and the same applies to the put tasks. Since the tasks w/o 5s safety margin work fine I assume we can safely drop or decrease that margin, which causes a more even load distribution.
### Minipeaks
As you can see at the begin of Q1, tasks are piling up while being inserted:
```
InsertPutNewNoisesTasks took 287.3933ms
InsertHavocsTasks took 727.5089ms
InsertPutFlagsTasks took 1029.3507ms
```
If we reduce our durability efforts, we should be able to eliminate that peak and improve db performance because our insert batches are smaller. However this sounds like a lengthy discussion and we should open a dedicated issue for that.

**Comment by Savallator** [comment]
You could see that all the time by looking at the timescale in log messages... but anyways...
This description:

> The results are roughly what we expected: Q1 has all putflags and getflags, Q2 has only havoc and getflags for old rounds, Q3 has all getflags for the current round and all getnoises, Q4 has no new tasks.
Makes no sense?

**Comment by Trolldemorted** [comment]
Does it not accurately describe the reality?

**Comment by Savallator** [comment]
No.

**Comment by Trolldemorted** [comment]
Woops... I amended my comment :)

**Comment by Savallator** [comment]
Its much better now...
